### PR TITLE
Feat: Who we are

### PR DESCRIPTION
**Pull request by Delyc**
## Issue ticket number and link
- ID:  #010
- Link: https://www.notion.so/apeunit/Who-We-Are-Section-8b1894fe80bb4ef2b3504543aaddddda

## Tasks completed
- [x] Coding who we are section
- [x] Making it responsive across all devices
 
## Tasks not completed
- None

## Screenshots (if needed)

Desktop:

image

Tablet:

image

Mobile:

image
image

### CODE REVIEW

**Review by Ntwali-Josue — CHANGES_REQUESTED** [review]
Hey @Delyc, please improve the contact us button on the mobile screen by decreasing its width. It should not take the whole screen width, see how it's behaving:  

image

**Review by Ntwali-Josue — APPROVED** [review]
Looks well 💯

**Review by mhenriette — APPROVED** [review]
looks good!!

**Review by alain-kubwayo — APPROVED** [review]
Looks good!

**Pull request merged**
